${TARGET}.axf: _frame0.o
${TARGET}.axf: _Frame1.o
${TARGET}.axf: _dict.o
${TARGET}.axf: ladder.o
${TARGET}.axf: imagedata.o
${TARGET}.axf: ladder_injector_3_final_ldx.o
${TARGET}.axf: ${ROOT}/lib/VPD-133-H-V/startup_gcc.o
${TARGET}.axf: ${ROOT}/lib/VPD-133-H-V/lwiplib_m4.o
${TARGET}.axf: ${ROOT}/lib/VPD-133-H-V.a
${TARGET}.axf: ${ROOT}/lib/commonlomf.a
${TARGET}.axf: ${ROOT}/lib/libgrwmf.a
${TARGET}.axf: ${ROOT}/lib/fonts.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_cyrillic.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_french.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_latin1s.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_cyrillic.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_french.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_latin1s.a
${TARGET}.axf: ${ROOT}/lib/font_abril_fatface.a
${TARGET}.axf: ${ROOT}/lib/font_crimson_pro.a
${TARGET}.axf: ${ROOT}/lib/font_dancing_script.a
${TARGET}.axf: ${ROOT}/lib/font_goblin_one.a
${TARGET}.axf: ${ROOT}/lib/font_kaushan_script.a
${TARGET}.axf: ${ROOT}/lib/font_pattaya.a
${TARGET}.axf: ${ROOT}/lib/font_roboto_condensed.a
${TARGET}.axf: ${ROOT}/lib/libdrivermf.a
